AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a NAT Gateway

Parameters:
  PublicSubnetId:
    Type: String
    Description: Subnet ID to associate the NAT Gateway with
    
  ProjectName:
    Type: String
    Description: Project name for tagging resources

Resources: 
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: NAT Gateway

Outputs:
  NatGatewayId:
    Description: The NAT Gateway ID
    Value: !Ref NatGateway
    Export:
      Name: NatGatewayId
