AWSTemplateFormatVersion: '2010-09-09'
Description: Module 3 - NAT Gateway for Private Subnet Access

Parameters:
  PublicSubnetId:
    Type: String
  ProjectName:
    Type: String
    Default: my-project

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-eip"

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-natgw"

Outputs:
  NatGatewayId:
    Value: !Ref NatGateway
  EipId:
    Value: !Ref ElasticIP
